### ISSUE TITLE
Detection of birefringes

### ISSUE THREAD

**Issue by dschick** [pyMatJ/pyGTM#3]
Hi again,

a question regarding the sorting of the `qs`:

https://github.com/pyMatJ/pyGTM/blob/1f62af2e3a80020bb31520f7db58577729ca27e9/GTM/GTMcore.py#L504

this statement is used to detect birefringes for a layer and to decide if eq (13) or (15) is used for qualculation of the `Cp`s.

I am wondering if the birefringes criterium for a single layer can't be done by checking for off-diagonal elements in the Euler-transformed `epsilon` 3x3 matrix?

in the best case one saves to calculate `Cp_t1` and `Cp_t2` and it would be also more simple and intuitive in my opinion.

Best

Daniel

**Comment by pyMatJ** [comment]
I am not 100% sure on this, the way I see it there is an implication but not 100% reciprocity: you need off-diagonal terms in the rotated `epsilon` tensor to get birefringence, but if by chance these give you degenerate eigenmodes then you want to sort again on the s/p pol. So the first criterion is really the power flow (i.e. the Cps)

**Comment by dschick** [comment]
Thanks a lot for the clarification. Then I stick with the criterion but will return the result, `isBirefringent` as output of the method instead of storing it in the layer. This makes also sense as the birefringence/sorting of the layer/qis can be zeta and frequency dependent.
